feat(): generate new contract.json after build provider-of-* package
easyops-cn/next-core pull request #1218
Opened 2021-12-02 08:33 UTC by qiaofengxi

Refs NEXT_BUILDER-1156

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2021-12-03 01:24 UTC, weareoutman commented on packages/build-config-factory/src/generateProviderContract.js
> +module.exports = function generateProviderDocsV2(pluginName) {
还没有地方使用？

2021-12-03 01:30 UTC, weareoutman commented on packages/build-config-factory/src/generateProviderContract.js
> +  const result = cp.spawnSync("git", ["clone", "-q", contractUrl, tmpDir]);
这个 contract 信息应该在 sdk 那边生成，否则可能造成 provider 代码和契约的版本不同步的情况（例如 provider 在使用 1.0 版本的 sdk，但是契约已经更新到 1.1 了，此时生成 provider 会使用 1.1 的契约，但代码还是 1.0 的）。

2021-12-03 01:47 UTC, weareoutman commented on packages/build-config-factory/src/generateProviderContract.js
> +        examples: doc.examples,
```suggestion
        ..._.pick(doc, ['name', ...]),
```

2021-12-06 01:39 UTC, qiaofengxi commented on packages/build-config-factory/src/generateProviderContract.js
> +  const result = cp.spawnSync("git", ["clone", "-q", contractUrl, tmpDir]);
done

2021-12-06 01:40 UTC, qiaofengxi commented on packages/build-config-factory/src/generateProviderContract.js
> +module.exports = function generateProviderDocsV2(pluginName) {
先给你看下这个生成逻辑先，可以了的话再使用

2021-12-06 02:31 UTC, weareoutman requested changes

2021-12-06 02:31 UTC, weareoutman commented on packages/build-config-factory/src/generateProviderContracts.js
> +  }
Use `fs.copySync`? https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy-sync.md

2021-12-06 02:31 UTC, weareoutman commented on packages/sdk-scripts/src/lib/Context.ts
> +          }),
`JSON.stringify` 已经美化了，不需要 prettier 了：

```suggestion
          JSON.stringify(contractDoc, null, 2),
```

2021-12-06 02:31 UTC, weareoutman commented on packages/sdk-scripts/src/loaders/loadService.ts
> +    if (isObject(i18nData)) {
这里是不是不要判断了，有问题直接报错，Fail Fast 原则。

2021-12-06 02:31 UTC, weareoutman commented on packages/sdk-scripts/src/loaders/loadService.ts
> +      if (isObject(modelI18nData)) {
同上。

2021-12-06 02:31 UTC, weareoutman commented on packages/sdk-scripts/src/utils.ts
> +    provider: `providers-of-${changeCase.paramCase(
这里 sdk 最好不要去理解 providers 的命名规则，sdk 是最底层的，底层的东西不要包含上层的逻辑。

这里可以直接输出契约的信息例如 `${serviceSeg}.${modelSeg}.${doc.name}`，然后交给 providers 那边的 build 再翻译成 provider 的名字。

2021-12-06 06:43 UTC, weareoutman approved these changes

2021-12-06 06:45 UTC, merged