feat(): React组件支持调用provider
easyops-cn/next-core pull request #1627
Opened 2022-03-15 10:35 UTC by WHChen-Alex

Closes NEXT_BUILDER-1457

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2022-03-15 11:54 UTC, weareoutman commented on package.json
> +    "@size-limit/file": "^7.0.5",
不要修改无关的组件版本

2022-03-15 12:16 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/useProvider.ts
> +    useProviderArgs(...args);
构件调用接口时，需要能在打包时统计每个构件用到的契约，并输出到构件包制品的 `deploy/contract.yaml` 中。

请参考以下文件实现契约分析：
- Contracts 预打包 `packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js`
- 打包后置脚本 `packages/build-config-factory/src/generateBrickContracts.js`

对于普通的 API 调用，原理是：
- SDK 代码中每个 API 通过特殊注释 `/**! @contract x.y.z@1.2.3 */` 来记录了该 API 对应的契约和版本；
- 构件包打包时，先使用 webpack 以每个构件的入口文件为单独入口，打出一份 contracts.log，结合 tree shaking 能力，此 log 可以单独识别每个构件使用的契约；
- 通过以上数据得到契约依赖信息。

为了能完整识别契约，构件必须要能静态分析出使用到契约，因此，此 `useProvider()` 有必要在打包环节限制只能使用可以静态分析的参数，例如 `useProvider({ provider: "a-b.x-y" })` 是合法的，但 `useProvider({ provider: someVar })` 是非法的、禁止使用的。

2022-03-15 13:18 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/useProvider.ts
> +    useProviderArgs(...args);
了解，先合并这个commit,然后改改脚本后再发布通知大家把。

2022-03-15 13:19 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/useProvider.ts
> +    useProviderArgs(...args);
还要增加特性的，下个commit应该是支持sdk生成的provider调用，最后写脚本做上面那个事情。

2022-03-15 13:21 UTC, WHChen-Alex commented on package.json
> +    "@size-limit/file": "^7.0.5",
淡定，还是draft~

2022-03-16 02:35 UTC, weareoutman requested changes

2022-03-16 02:35 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
> +          const data = await request.query("easyops.custom_api@test", {
这个操作很难被静态分析，建议先不要开放这种调用。

2022-03-16 02:35 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
> +    expect(wrapper.find("ToDo").text()).toBe("rendered");
这个测试用例似乎没有对 suspense 的效果进行有效的断言？另外，据官方文档介绍，Suspense 只能结合 `React.lazy` 使用：https://reactjs.org/docs/react-api.html#reactsuspense

2022-03-16 06:31 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/fetchProviderArgs.ts
> +  const args = (await getArgsOfCustomApi(provider, originalArgs)) as FetchArgs;
这个只能调用 flow builder 的 api 是吧？

2022-03-16 08:10 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/fetchProviderArgs.ts
> +  const args = (await getArgsOfCustomApi(provider, originalArgs)) as FetchArgs;
是的，我下面有评论的

> "还要增加特性的，下个commit应该是支持sdk生成的provider调用(淡化SDK这个概念)，最后写脚本做上面那个事情"

2022-03-16 08:25 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
> +    expect(wrapper.find("ToDo").text()).toBe("rendered");
这里主要是利用了suspense的机制，是挺灵活的，很多hooks都会这么做的。
经过测试没什么问题。

2022-03-16 08:30 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
> +          const data = await request.query("easyops.custom_api@test", {
我先不通告？  解决了静态分析问题在说，可以先合并？

2022-03-16 08:40 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
> +          const data = await request.query("easyops.custom_api@test", {
好，后面如果不能支持的话，这个 query 的能力需要直接下掉。

2022-03-16 08:42 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
> +    expect(wrapper.find("ToDo").text()).toBe("rendered");
我的意思是，你的测试用例没有真正测出 suspense 是否生效，因为无论是否生效，这个用例都会通过。不过你后面再补充完善吧。

2022-03-16 08:45 UTC, weareoutman commented on packages/brick-kit/src/hooks/useProvider/fetchProviderArgs.ts
> +  const args = (await getArgsOfCustomApi(provider, originalArgs)) as FetchArgs;
这里，我对这个 `useProvider` 支持普通 sdk 的可行性存在疑问，因为 sdk 包含了契约的内容，接口调用必需要先知道契约的一些关键信息（比如 URL 等），但框架上是对契约持「不可知论」的，因此没有契约信息就没法调用接口。

2022-03-16 08:46 UTC, weareoutman approved these changes

2022-03-16 08:46 UTC, merged

2022-03-16 08:48 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/fetchProviderArgs.ts
> +  const args = (await getArgsOfCustomApi(provider, originalArgs)) as FetchArgs;
我的想法是想利用编排的`useProvider`里面的那种方式调用，其实还是加载provider-brick的然后调用resolve方法。

2022-03-16 08:54 UTC, WHChen-Alex commented on packages/brick-kit/src/hooks/useProvider/fetchProviderArgs.ts
> +  const args = (await getArgsOfCustomApi(provider, originalArgs)) as FetchArgs;
[这里这段代码](http://github.com/easyops-cn/next-core/blob/1fe60963f96b4cddd889837da3ae5dd19f472d46/packages/brick-kit/src/core/Resolver.ts#L235-L235)