feat(): useProviderHook契约收集
easyops-cn/next-core pull request #1678
Opened 2022-03-29 08:29 UTC by WHChen-Alex

Refs NEXT_BUILDER-1470

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2022-03-29 08:34 UTC, weareoutman commented on packages/webpack-config-factory/src/loaders/provider-hook-contracts-loader.js
> +  const ast = parser.parse(content, { sourceType: "module" });
这里对每个 js 文件都要执行一次多余的语法解析，不必要的性能开销太大，能否参考 `packages/webpack-config-factory/src/bricks/ScanCustomElementsPlugin.js` 的实现，直接使用 webpack 解析好的 AST？

2022-03-29 08:46 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/loaders/provider-hook-contracts-loader.js
> +  const ast = parser.parse(content, { sourceType: "module" });
okk

2022-03-31 01:32 UTC, weareoutman requested changes

2022-03-31 01:32 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +            expression.callee.property.name === "query"
这个 `query` 就不要捕获了吧，很容易误报。

2022-03-31 01:32 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +              if (firstArg?.type === "Literal") {
前面的条件已经决定不需要 `?.`

```suggestion
              const firstArg = expression.arguments[0];
              if (firstArg.type === "Literal") {
```

2022-03-31 01:32 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +                if (/^(providers-of-)[a-z-]*.[a-z-]*/.test(firstArg.value)) {
名字中允许有数字哦。

2022-03-31 01:37 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +                if (/^(providers-of-)[a-z-]*.[a-z-]*/.test(firstArg.value)) {
api允许还是都允许有？

`(providers-of-)[a-z-]*.[a-z-\d]*`

2022-03-31 01:55 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +            expression.callee.property.name === "query"
不捕获`query`感觉更容易误报，还是说不要打印warnin?

2022-03-31 02:01 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +            expression.callee.property.name === "query"
所以我之前就建议不要开放 `query` 的 API，限制开发者的用法，尽量用能被静态分析的接口形式。

2022-03-31 02:42 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +            expression.callee.property.name === "query"
`query`里面的值我也会加`/^(providers-of-)[a-z-\d]*.[a-z-\d]*/`这个来效验的，一个MemberExpression并且name是query，而且第一个参数满足provider的正则，这几率很小很小吧。

2022-03-31 02:47 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +            expression.callee.property.name === "query"
好，加上正则可以，不过你的正则没有保护 flow api ？

2022-03-31 03:31 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +            expression.callee.property.name === "query"
加上了，你看下

2022-03-31 04:05 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +              if (firstArg?.type === "Literal") {
这里也改了

2022-03-31 06:59 UTC, weareoutman requested changes

2022-03-31 06:59 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +  /^(easyops.api.)[a-zA-Z-_\d]*.[a-zA-Z-_\d]*@[a-zA-Z-_\d]*:(\d+\.)?(\d+\.)?(\d+)/;
这两个正则都有点问题:
- 几处点号 `.` 都没有转义
- 应该是全匹配，末尾应该加上 `$`?
- Flow API 好像可以不加最后的版本号？

2022-03-31 08:15 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +  /^(easyops.api.)[a-zA-Z-_\d]*.[a-zA-Z-_\d]*@[a-zA-Z-_\d]*:(\d+\.)?(\d+\.)?(\d+)/;
> Flow API 好像可以不加最后的版本号？

我问了jo他说如果不加版本号的话会跑到最初妮珊写的那版契约去，但是那边的服务都下掉了，现在都是加版本号的

2022-03-31 08:16 UTC, weareoutman commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +  /^(easyops.api.)[a-zA-Z-_\d]*.[a-zA-Z-_\d]*@[a-zA-Z-_\d]*:(\d+\.)?(\d+\.)?(\d+)/;
ok 那你改下其他的。

2022-03-31 08:17 UTC, WHChen-Alex commented on packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
> +  /^(easyops.api.)[a-zA-Z-_\d]*.[a-zA-Z-_\d]*@[a-zA-Z-_\d]*:(\d+\.)?(\d+\.)?(\d+)/;
我推了  你看下

2022-03-31 15:07 UTC, merged