feat(): support lifeCycle.onIntersectionChange
easyops-cn/next-core pull request #1855
Opened 2022-05-24 09:39 UTC by L-fingerprint

refs NEXT_BUILDER-1616

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [X] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [X] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [X] 给新特性添加了单元测试。
- [X] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2022-05-24 09:43 UTC, SailorF commented on packages/brick-kit/src/core/BrickNode.ts
> +  private observer: any;
observer是已知类型的, 非any

2022-05-24 09:50 UTC, L-fingerprint commented on packages/brick-kit/src/core/BrickNode.ts
> +  private observer: any;
已修改

2022-05-24 10:09 UTC, weareoutman commented on packages/brick-kit/src/core/BrickNode.ts
> +    if (brick.lifeCycle?.onIntersectionChange) {
确实这里的实现其实并不是 `onIntersectionChange`，用 `onLazyLoad` 也不是很好，可以换成 `onScrollIntoView`。

同时 `threshold` 不再需要，可以直接给个经验值，比如 `0.1`，`handlers` 字段也不再需要，直接铺出来。

```yaml
onScrollIntoView:
  - action:  console.log
```

2022-05-24 10:17 UTC, weareoutman commented on packages/brick-kit/src/core/reconciler.ts
> +  context: LocationContext
不要跨这么多级传递 context，能参考 `onPageLoad` 在 `LocationContext` 里收集并处理吗？

2022-05-24 10:18 UTC, SailorF commented on packages/brick-kit/src/core/BrickNode.ts
> +    if (brick.lifeCycle?.onIntersectionChange) {
还是有必要对外暴露 threshold的, 因为存在场景, 构件距上可能存在一定距离, 用户希望滚动到特定位置才进行数据请求, 没有threshold可能就没办法满足这种场景了

2022-05-24 10:33 UTC, weareoutman commented on packages/brick-kit/src/core/reconciler.ts
> +  context: LocationContext
这里只是注册 observer 呀，又不是立即发起请求。

2022-05-24 10:35 UTC, weareoutman commented on packages/brick-kit/src/core/BrickNode.ts
> +    if (brick.lifeCycle?.onIntersectionChange) {
好，这个你们评估吧，关系不大。

2022-05-24 10:35 UTC, L-fingerprint commented on packages/brick-kit/src/core/BrickNode.ts
> +    if (brick.lifeCycle?.onIntersectionChange) {
`threshold`这个不需要暴露出去吗？在有些场景，我觉得还是可以用到的吧

2022-05-24 10:46 UTC, L-fingerprint commented on packages/brick-kit/src/core/reconciler.ts
> +  context: LocationContext
可是我是在`BrickNode` 这个注册监听，然后当超过阈值之后，我就会去调用 `LocationContext`里面的方法也，这个我不传入，怎么拿呢？

2022-05-24 10:56 UTC, weareoutman commented on packages/brick-kit/src/core/reconciler.ts
> +  context: LocationContext
我的意思是把注册监听的逻辑都搬到 `LocationContext` 里去。

2022-05-24 11:04 UTC, L-fingerprint commented on packages/brick-kit/src/core/reconciler.ts
> +  context: LocationContext
这里我需要在dom挂载之后，我才能注册监听也，在`LocationContext`这里我无法知道dom已经挂载完了？否则我就需要把`mountTree`逻辑也需要搬过去吗？

2022-05-25 02:33 UTC, SailorF approved these changes

2022-05-25 02:57 UTC, weareoutman requested changes

2022-05-25 02:57 UTC, weareoutman commented on packages/brick-kit/src/core/LocationContext.ts
> +      $$observe: () => observer.observe(document.querySelector(`#${id}`)),
没必要设置 id，这会引起副作用。设置`brick: RuntimeBrick` 里存有 `brick.element` 的引用，你这里记录 `brick` 即可，后面可以通过 `brick.element` 拿到构件元素。

2022-05-25 02:57 UTC, weareoutman commented on packages/brick-types/src/manifest.ts
> +  threshold: number;
```suggestion
  threshold?: number;
```

2022-05-25 02:59 UTC, L-fingerprint commented on packages/brick-kit/src/core/LocationContext.ts
> +      $$observe: () => observer.observe(document.querySelector(`#${id}`)),
好

2022-05-25 06:12 UTC, weareoutman approved these changes

2022-05-25 06:13 UTC, merged