feat(): standalone support launchpad info
easyops-cn/next-core pull request #2232
Opened 2022-09-20 18:45 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2022-09-21 02:15 UTC, weareoutman requested changes

2022-09-21 02:15 UTC, weareoutman commented on packages/brick-kit/src/core/Kernel.ts
> +        ),
这个 loadMicroApps 以及 reloadMicroApps 的逻辑我建议调整下，目前两个东西混用了，仅看到三个用途：

1. load: launchpad 显示的应用列表；
2. reload: launchpad 自动轮询「状态为安装中」的微应用（如果有）；
3. reload: 登录/注册后重新拉取应用列表。

在独立打包模式下，需要把 bootstrap 的应用列表和 launchpad 的应用列表区分开来，

对于第一点：bootstrap 不需要提前拉取全量应用列表，即这里的 launchpadInfo，可以在 launchpad 打开时再拉取它（并且单独存放，不要存到 bootstrap 里了），或者在空闲阶段拉取，不要阻塞页面渲染。

对于第二点：复用第一点的拉取方法。

对于第三点：不需要拉取了，独立打包在登录后发生的是「硬跳转」，不需要重新拉应用列表。

对于普通打包模式，之前的逻辑可以保持不变。

2022-09-21 02:15 UTC, weareoutman commented on packages/brick-kit/src/core/Kernel.ts
> +        ),
reload 可能发生多次调用，这里 launchpadInfo 似乎每次都会叠加，这个逻辑不对。另外，这里拉取的 storyboards 没有像 `loadMicroApps` 后面那样对数据进行一些后置加工。

2022-09-21 02:15 UTC, weareoutman commented on packages/brick-kit/src/core/Kernel.ts
> +        storyboards: launchpadInfo.storyboards.concat(
这个追加会导致[独立打包的跨应用跳转](https://github.com/easyops-cn/next-core/blob/8520f720888193f1a8d3f683db3b8b429d09658c/packages/brick-kit/src/internal/historyExtended.ts#L164-L170)的能力丢失。这个如果使用下述建议的「把 bootstrap 的应用列表和 launchpad 的应用列表区分开来」可以避免。

2022-09-22 06:28 UTC, SailorF commented on packages/brick-kit/src/core/Kernel.ts
> +      const launchpadInfo = await this.getLaunchpadInfo();
那么就把这个接口请求迁移至 launchpad 构件上?

2022-09-22 06:47 UTC, closed without merging