feat(): support containers Component
easyops-cn/next-core pull request #2814
Opened 2023-03-15 06:23 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-03-15 06:50 UTC, weareoutman requested changes

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/src/micro-view/index.tsx
> +          margin: hasToolbar || pageTitle ? "9px 0" : "",
这个样式最好通过 css attr selector 实现，这样 `hasToolbar` 的变更不用触发 MicroViewElement 重新渲染

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/src/micro-view/index.tsx
> +      this.hasToolbar = true;
这里需要判断插槽中是否有元素来决定

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/src/micro-view/index.tsx
> +  accessor hasToolbar: boolean | undefined;
没有被 `@property` 修饰，不会有 `[has-toolbar]` 的 attr 映射

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/src/tab-list/index.tsx
> +        });
这个逻辑没啥必要，没有什么实际场景会让系统自动补一个 `Tab 1` 这样的标题

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/src/tab-list/index.tsx
> +        });
还是之前说的，底层上参考下业界的实现，上层来进行包装，

https://shoelace.style/components/tab-group

https://explore.fast.design/components/fast-tabs

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/src/category/index.tsx
> +  accessor category: categoryProps[];
如果是列表，最好用复数 
```suggestion
  accessor categories: categoryProps[];
```

2023-03-15 06:50 UTC, weareoutman commented on bricks/containers/package.json
> +    "@next-core/runtime": "^0.0.0",
这两个依赖只在需要时添加，通常不需要，只有当使用 runtime 接口或 useBrick 时才需要。
```suggestion
```

2023-03-16 04:10 UTC, weareoutman requested changes

2023-03-16 04:10 UTC, weareoutman commented on bricks/containers/src/micro-view/index.tsx
> +      }
```suggestion
      this.hasToolbar = slotToolbar.assignedElements().length > 0;
```

2023-03-16 04:10 UTC, weareoutman commented on bricks/containers/src/micro-view/index.tsx
> +        hasToolbar={this.hasToolbar}
```suggestion
```

2023-03-16 04:16 UTC, weareoutman commented on bricks/containers/src/micro-view/index.tsx
> +        hasToolbar={this.hasToolbar}
关键是删除这一行，这样 `this.hasToolbar` 变更时才不会多余地触发 MicroViewElement 的重新渲染。

2023-03-16 04:20 UTC, SailorF commented on bricks/containers/src/micro-view/index.tsx
> +        hasToolbar={this.hasToolbar}
好了

2023-03-16 04:40 UTC, weareoutman approved these changes

2023-03-16 04:40 UTC, merged