feat(): build brick supports analysis typescript
easyops-cn/next-core pull request #3189
Opened 2023-06-19 08:01 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-06-19 08:56 UTC, weareoutman requested changes

2023-06-19 08:56 UTC, weareoutman commented on packages/build-next-bricks/src/scanBricks.js
> -          importKind === "value"
这里原始作用是识别构件依赖关系，避免 type 的引用也产生构件的依赖关系。这里需要保障之前的逻辑正常工作，否则将产生很多不必要的构件依赖

2023-06-19 08:56 UTC, weareoutman commented on packages/build-next-bricks/src/scanBricks.js
> +    let brickManifest;
一个文件中不排除有多个构件定义（特别是后面要支持的 provider 构件），这里不能假设一个文件对应一个构件定义

2023-06-19 08:56 UTC, weareoutman commented on packages/build-next-bricks/src/scanBricks.js
> +      brickDoc.interfaces = (brickDoc.interfaces || []).concat(
上次好像说过，这个数据最好不要放到现有的 manifest.json 里，因为 manifest.json 更基础、消费的场景不一样。而 TS 类型数据的体积可能很大，避免在基础场景里也去加载这些 TS 类型数据了。

2023-06-19 08:56 UTC, weareoutman commented on packages/build-next-bricks/src/scanBricks.js
> +      brickDoc.interfaces = (brickDoc.interfaces || []).concat(
把现在生成的最终数据发出来看看

2023-06-19 09:07 UTC, SailorF commented on packages/build-next-bricks/src/scanBricks.js
> -          importKind === "value"
那这样的话就需要多出一套逻辑专门读取类型文件了

2023-06-19 10:02 UTC, weareoutman commented on packages/build-next-bricks/src/utils.js
> +      .join("|");
类型信息不要直接都转成字符串了，最好记录详细的信息，这样最终渲染的时候可以更灵活处理引用关系（可以给引用的类型加链接），例如 

<img width="480" alt="image" src="https://github.com/easyops-cn/next-core/assets/2338946/8b7fe6a3-4c4f-4bef-a6c3-fc58b897d59b">

2023-06-19 10:54 UTC, SailorF commented on packages/build-next-bricks/src/utils.js
> +      .join("|");
有个想法， 如果识别到是 reference, 那么字符的组成则为 ##name, 然后在页面渲染的时候，做特殊渲染

2023-06-19 10:56 UTC, SailorF commented on packages/build-next-bricks/src/utils.js
> +      .join("|");
比如这里实际上字符为:  `Partial<##ModelSearchSort>[]`
然后页面渲染的时候变成:
<span>Partial<a href="/xxx/#ModelSearchSort">ModelSearchSort</a>[]</span>

2023-06-19 10:58 UTC, weareoutman commented on packages/build-next-bricks/src/utils.js
> +      .join("|");
这种做成正则匹配的话不够准确，比如如果有个字符串的类型的内容就是 "##name" 呢？做成结构化数据，后面可以灵活消费

2023-06-20 01:01 UTC, weareoutman requested changes

2023-06-20 01:54 UTC, SailorF commented on packages/build-next-bricks/src/scanBricks.js
> +            return scanByImport(fileInfo, "", "");
是的，因为读取构件的时候会忽略 type 类型的 import，这里就统一获取所有构件的 import，识别到其中还没 import 的部分，进行解析

2023-06-20 03:42 UTC, weareoutman requested changes

2023-06-20 03:42 UTC, weareoutman commented on packages/build-next-bricks/src/utils.js
> +      value = `"${typeAnnotation.literal.value}"`;
没有必要给它加个 `""`，消费时可以根据类型自己处理

2023-06-20 03:42 UTC, weareoutman commented on packages/build-next-bricks/bin/build-next-bricks.js
> +          path.join(distDir, "types.json"),
这个只是 `--manifest-only` 时的逻辑，还需要在 `packages/build-next-bricks/src/EmitBricksJsonPlugin.js` 里生产 `types.json`

2023-06-20 07:38 UTC, weareoutman commented on packages/build-next-bricks/src/utils.js
> +        left: typeName.left.name,
根据 babel 类型定义，`TSQualifiedName::left` 可能也是 `Identifier | TSQualifiedName`，如果是后者，没有 `name`

2023-06-20 10:09 UTC, weareoutman commented on packages/build-next-bricks/src/utils.js
> +      });
这两个 `stringLiteral` 的意义完全不一样，上面是 JS 的 value，而下面是 ts keyword 的类型

2023-06-20 10:21 UTC, weareoutman approved these changes

2023-06-20 10:25 UTC, merged