feat(): support set watermark
easyops-cn/next-core pull request #3980
Opened 2024-03-13 06:55 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2024-03-13 07:18 UTC, weareoutman requested changes

2024-03-13 07:18 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
如果

1. 进入一个 app 开启了show-watermark
2. 跳转进入另一个 app 未开启 show-watermark

似乎不会清理掉已有的 watermark？

2024-03-13 07:50 UTC, SailorF commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
通过 特性开关 和 miscSettings 控制，统一控制，按道理不会出现这种场景

Developer 会识别版本，如果 content 为空，则水印也变成空的了

2024-03-13 07:58 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
app 可以单独控制开关，比如有个别应用是非常公开的信息，不希望打水印

2024-03-13 07:59 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +      flags["show-developer-watermark"] && isDeveloper ? "Developer" : "",
这个应该是显示为 `Development` 吧？

2024-03-13 08:13 UTC, SailorF commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
这里是在 Router 逻辑里，每次 render 都会走进这个方法，个别 APP 配置了 `watermarkConfig`, 水印是可以被覆盖的。
不过只局限于 watermarkConfig,  `Development ` 和 `username` 都会展示

2024-03-13 08:14 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +      flags["show-developer-watermark"] && isDeveloper ? "Developer" : "",
记得开关名也对应调整下

2024-03-13 08:15 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
> 如果
> 
> 1. 进入一个 app 开启了show-watermark
> 2. 跳转进入另一个 app 未开启 show-watermark
> 
> 似乎不会清理掉已有的 watermark？

所以我上面这个现象是否成立？但预期应该是要清理？

2024-03-13 08:19 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
misc 一样可以 app 单独控制

2024-03-13 08:20 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
> app 可以单独控制开关，比如有个别应用是非常公开的信息，不希望打水印

另外本身就可能有按 app 单独控制的场景

2024-03-13 08:23 UTC, weareoutman commented on packages/runtime/src/setWatermark.ts
> +    loadBricksImperatively([WATEMARK_BRICKNAME], getBrickPackages()).then(
另外有个问题，你这个其实要求 advanced 也变成公共组件，否则这个构件只有应用依赖了这个包的较新版本才行

2024-03-13 08:24 UTC, SailorF commented on packages/runtime/src/setWatermark.ts
> +  if (!flags["show-watermark"]) {
目前有三个特性开关：
- `show-watermark` (开启后支持根据 MISC 配置展示水印)
- `show-developer-watermark`(开启后 app verison 等于 0.0.0 时，会展示 Development 水印)
- `show-user-watermark` (开启后会展示用户名称)

将这三个特性开关全部移动至 `MISC` 吧。
特性开关控制颗粒度太粗了，不适合这种场景。

2024-03-13 08:26 UTC, SailorF commented on packages/runtime/src/setWatermark.ts
> +    loadBricksImperatively([WATEMARK_BRICKNAME], getBrickPackages()).then(
所以我还是把它挪到 basic-NB 里？😂

2024-03-15 02:53 UTC, weareoutman approved these changes

2024-03-15 02:54 UTC, merged