feat(): brick-next接入rum
easyops-cn/next-core pull request #4221
Opened 2024-06-04 09:26 UTC by WHChen-Alex

Closes APM-996

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2024-06-04 09:58 UTC, weareoutman requested changes

2024-06-04 09:58 UTC, weareoutman commented on packages/easyops-analytics/src/SkywalkingAnalysis.ts
> +  ClientMonitor?.setPerformance({
如果 `setPerformance()` 调用时，`ClientMonitor` 还在加载中，那么报告就被忽略了？

可以判断下，没加载就先放到队列里，加载完成时刷一遍队列。

下面的 `reportFrameErrors` 同理

2024-06-04 09:58 UTC, weareoutman commented on packages/brick-container/serve/getEnv.js
> +    process.env.USE_SKYWALKING_ANALYSIS === "true";
你上面定义了这个 flag 类型是 string，但是这里下面的判断又可能是 boolean，统一下类型吧

2024-06-04 10:02 UTC, weareoutman commented on packages/brick-container/serve/getEnv.js
> +    );
这段输出的 if 判断是弱类型的 truthy 判断，但是 html 里又是 `"true" === "true"` 的强判断，统一一下。不然如果传入一个 `--use-skywalking-analysis=1` 时，会输出提示使用了，但页面实际没启用。

2024-06-04 12:36 UTC, WHChen-Alex commented on packages/easyops-analytics/src/SkywalkingAnalysis.ts
> +  ClientMonitor?.setPerformance({
这个库size很小大概31kb，经过我很多次测试，基本不会有那种情况，就没加。

现在加上了

2024-06-04 12:37 UTC, WHChen-Alex commented on packages/brick-container/serve/getEnv.js
> +    process.env.USE_SKYWALKING_ANALYSIS === "true";
已解决，为字符串类型

2024-06-04 12:37 UTC, WHChen-Alex commented on packages/brick-container/serve/getEnv.js
> +    );
已解决

2024-06-04 12:56 UTC, weareoutman requested changes

2024-06-04 12:56 UTC, weareoutman commented on packages/easyops-analytics/src/SkywalkingAnalysis.ts
> +          ...opts,
貌似队列里的 opts 和下面调用的参数并不一样？

建议把队列直接改成缓存包装好的函数 task，然后 task 根据是否有 ClientMonitor 选择直接执行还是进入队列。这样不用在队列里去记录方法名和参数列表。

```js
const task = () => {
  ClientMonitor.setPerformance(...)
}
if (ClientMonitor) {
  task();
} else {
  queue.push(task);
}
```

2024-06-04 14:20 UTC, WHChen-Alex commented on packages/easyops-analytics/src/SkywalkingAnalysis.ts
> +          ...opts,
已修改了

2024-06-05 01:14 UTC, weareoutman approved these changes

2024-06-05 01:14 UTC, merged