feat(): add CustomEditorRegisty
easyops-cn/next-core pull request #4225
Opened 2024-06-05 07:17 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2024-06-05 07:27 UTC, weareoutman requested changes

2024-06-05 07:27 UTC, weareoutman commented on packages/runtime/src/CustomEditors.spec.ts
> +describe("CustomProcessors", () => {
这名字都错了吧

2024-06-05 07:27 UTC, weareoutman commented on packages/build-next-bricks/src/scanBricks.js
> +            if (!fullName.endsWith("--editor")) {
建议不要加 --editor 后缀了，editor 里面肯定是 editor，这里直接复用构件名的 regex

2024-06-05 07:27 UTC, weareoutman commented on packages/loader/src/stableLoadBricks.ts
> +        if (p.editors.includes(item)) {
这里是构件的加载逻辑了，editors 应该参考 processors 的逻辑而不是构件

2024-06-05 09:49 UTC, weareoutman requested changes

2024-06-05 09:49 UTC, weareoutman commented on packages/loader/src/stableLoadBricks.ts
> +        }
噢，这里我搞错了，和 processors 不一样，不过和 bricks 也不一样，bricks 之前做了个重名 deprecated 构件的处理，editors 不需要，简单处理下就好

2024-06-05 10:06 UTC, weareoutman commented on packages/loader/src/stableLoadBricks.ts
> +        }
不要把 bricks 和 editors 的查找混在一起了，比如假设现在有构件 `eo-button`，但是还没写 editor 的，按目前的逻辑，会返回找到了。

2024-06-05 10:07 UTC, weareoutman commented on packages/loader/src/stableLoadBricks.ts
> +    if (type === "processors" || type === "editors" || item.includes(".")) {
这儿我之前搞错了
```suggestion
    if (type === "processors" || item.includes(".")) {
```

2024-06-05 10:29 UTC, weareoutman approved these changes

2024-06-06 01:27 UTC, weareoutman commented on packages/loader/src/stableLoadBricks.ts
> +export function enqueueStableLoadEditors(
这个函数应该不会用到，可以去掉。其他的要加上单元测试

2024-06-06 02:28 UTC, weareoutman commented on packages/loader/src/stableLoadBricks.ts
> +export function enqueueStableLoadEditors(
删错了？我说的这个可以去掉...

2024-06-06 02:32 UTC, SailorF commented on packages/loader/src/stableLoadBricks.ts
> +export function enqueueStableLoadEditors(
删错了..

2024-06-06 03:37 UTC, weareoutman approved these changes

2024-06-06 03:37 UTC, merged