Sailorshe/master/use brick support template
easyops-cn/next-core pull request #898
Opened 2021-08-23 12:12 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

新增特效说明:
- 目前支持useBrick的custom-template编写, 并且保证数据正常传递(TPL, DATA, EVENT)
- useBrick中custom-template对外暴露的slots, 可进行正常渲染

重点修改: 
#### LocationContext.ts
1. LocationContext采用了单例模式进行使用;
2. 在mouteBrick的时候, 判断properties中是否存在useBrick, 如果存在则获取当前tplContextId, 并给useBrick以及其底下的slots进行tplContextId赋值, 后续useBrick会根据这个tplContextId获取TPL的context;
3. 对外暴露tplContext获取方式

#### BrickAsComponent.ts
1. 获取当前locationContext实例, 后续获取tplContext会使用到;
2. isBrickAvailable增加getTplVariables方法, 可根据当前brick的tplContextId获取到当前brick的context, 用以transform使用;
3. 通过getTagNameCustomTemplate方法判断当前useBrick是否是custom-template, 如若是,  进入新的逻辑判断中:
- 设置expandCustomTemplate的参数, tplConf, proxyConf
- 获取到expandCustomTemplate结果设置为template, 通过React.createElement创建element元素
- 遍历template, useBricks中的slots, 传入SingleBrickAsComponent组件中, 进行对子构件的渲染
- 在遍历过程中, 由于slotItem缺少了proxy数据, 需要与外层proxyConf进行结合, 后续会调用
4. 在创建完element后, 会调用方法 runtimeBrick, 在runtimeBrick方法中, 新的改造有:
- 先判断useBrick中是否存在tplContextId,如果存在,会给transfromOption添加getTplVariables方法, 方便后续evaluate计算使用
- 设置brick值, 判断是否是custom-template, 并且对template.slots或useBricks进行处理, 如果各自对象上的refForProxy不等于undefined, 则将refForProxy赋值等于自己(保持内存地址的一致性), 后续设置proxy会用到
5. 设置properties中的refProperty值
6. 进入 innerRefCallback, 设置完elmenet后, 回调用 handleProxyOfCustomTemplate方法, 对template的proxy进行赋值;

TODO:
- useBrick中custom-template对外暴露的slots 事件目前还没办法正常绑定
- 存在多级事件传递场景, 目前还不支持

- 单元测试尚未补全

2021-08-24 01:18 UTC, weareoutman commented
👏 That's a good start!

2021-08-24 01:33 UTC, weareoutman commented on packages/brick-kit/src/core/LocationContext.ts
> +    if (!LocationContext.instance.get(key)) {
`LocationContext` 的实例是作为 `Router` 的私有属性设置的，不希望对外暴露，而 `LocationContext` 这个类作为 developHelper 对外暴露了，如果将它改为单例模式，相当于对外暴露了系统的 `LocationContext` 的实例，这是不希望发生的。建议参考 `_internalApiGetCurrentContext` 的实现将需要的数据装为一个内部的 `_internalApi...`。

2021-08-24 02:51 UTC, weareoutman commented on packages/brick-kit/src/core/LocationContext.ts
> +    }
这些操作我感觉是多余的吧，`expandBrickInTemplate` 会记录子构件的 `tplContextId` 呀？

2021-09-01 01:31 UTC, weareoutman requested changes

2021-09-01 01:31 UTC, weareoutman commented on packages/brick-kit/src/BrickAsComponent.tsx
> +          properties: data as Record<string, unknown>,
这个用 data 作为 properties，感觉不对吧？

2021-09-01 01:31 UTC, weareoutman commented on packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
> +    ?.useBrick as UseBrickConf;
1. template 中本来就可以使用 useBrick，你这个特性是“让 useBrick 支持使用 template”；
2. `useBrick` 不是只出现在 properties  的第一层属性的，还可能是任意内层的，比如 `properties.itemBricks.useBrick` 等等。

2021-09-01 01:31 UTC, weareoutman commented on packages/brick-kit/src/core/CustomTemplates/handleProxyOfCustomTemplate.ts
> +          if (!node[propName]) {
1. `node[propName]` 是判断属性值的，而不是判断这个属性是否已定义的；
2. 这里理论上不会重入的，不应该被多次定义，不应该在这里判断，而应该想办法在上层避免重入。

2021-09-01 01:33 UTC, weareoutman commented on packages/brick-kit/src/core/LocationContext.ts
> +    const useBrick: UseBrickConf = brick.properties.useBrick;
这个同上：useBrick 不是只出现在 properties 的第一层属性的。

2021-09-13 01:56 UTC, weareoutman commented
> ## Pull Request Test Coverage Report for [Build 1226988375](https://coveralls.io/builds/42811161)
> * **105** of **127**   **(82.68%)**  changed or added relevant lines in **7** files are covered.
> * **1** unchanged line in **1** file lost coverage.
> * Overall coverage decreased (**-0.1%**) to **94.64%**
> 
> Changes Missing Coverage	Covered Lines	Changed/Added Lines	%
> [packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts](https://coveralls.io/builds/42811161/source?filename=packages%2Fbrick-kit%2Fsrc%2Fcore%2FCustomTemplates%2FexpandCustomTemplate.ts#L235)	9	11	81.82%
> [packages/brick-kit/src/core/LocationContext.ts](https://coveralls.io/builds/42811161/source?filename=packages%2Fbrick-kit%2Fsrc%2Fcore%2FLocationContext.ts#L756)	18	20	90.0%
> [packages/brick-kit/src/BrickAsComponent.tsx](https://coveralls.io/builds/42811161/source?filename=packages%2Fbrick-kit%2Fsrc%2FBrickAsComponent.tsx#L163)	49	67	73.13%
> Files with Coverage Reduction	New Missed Lines	%
> [packages/brick-kit/src/internal/menu.ts](https://coveralls.io/builds/42811161/source?filename=packages%2Fbrick-kit%2Fsrc%2Finternal%2Fmenu.ts#L290)	1	98.14%
> Totals	[![Coverage Status](https://camo.githubusercontent.com/2ef188b7b0579cae8dcddd3fc6162bef8b15e8a63a46f5bf834c82e6b7fc242c/68747470733a2f2f636f766572616c6c732e696f2f6275696c64732f34323831313136312f6261646765)](https://coveralls.io/builds/42811161)
> Change from base [Build 1181271402](https://coveralls.io/builds/42499942):	-0.1%
> Covered Lines:	5914
> Relevant Lines:	6154
> ##### 💛 - [Coveralls](https://coveralls.io)

@SailorF 有 20+ 行新增代码没有测试覆盖，需要尽量尝试覆盖下。

2021-09-13 02:03 UTC, weareoutman commented on packages/brick-kit/src/core/CustomTemplates/handleProxyOfCustomTemplate.ts
> +              refElement.$$proxyEvents.splice(index, 1);
在 `forEach` 中修改原数组，会有意外发生的。

2021-09-13 02:09 UTC, weareoutman commented on packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
> +  // 递归遍历properties下UseBrick, 目的是为了获取底下所有代理属性
这一步没看懂是做什么，之前讨论过，原来就已支持在 template 中使用 useBrick。

2021-09-14 08:48 UTC, weareoutman requested changes

2021-09-14 08:48 UTC, weareoutman commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
这个接口是内部使用的，不要对外暴露

2021-09-14 08:48 UTC, weareoutman commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
包括那几个 dll snapshot 也需要同步去掉。

2021-09-14 08:48 UTC, weareoutman commented on packages/brick-kit/src/core/LocationContext.ts
> +              setTplIdForUseBrick((slotItem as any)[slotItem.type]);
`slotItem.type` 可能没有填写的，实际上 useBrick 的 slots 只能是 bricks，这里可以直接使用 `"bricks"`。

2021-09-14 08:51 UTC, SailorF commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
这里为了方便单元测试编写才暴露出去的

2021-09-14 08:58 UTC, SailorF commented on packages/brick-kit/src/core/LocationContext.ts
> +              setTplIdForUseBrick((slotItem as any)[slotItem.type]);
get

2021-09-14 09:56 UTC, weareoutman commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
可以呀，但不要在 brick-kit 包中对外暴露了。

2021-09-14 10:00 UTC, SailorF commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
不写build的时候报错了, 是它提示我copy的

2021-09-14 10:54 UTC, weareoutman commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
你把它从对外接口中去除，就不会有这些报错了。这个报检查的目的就是发现这些意外暴露的对外接口。

2021-09-14 12:08 UTC, weareoutman commented on etc/brick-kit.api.md
> +export const handleProxyOfParentTemplate: (brick: RuntimeBrick, tplContextId: string, tplContext: CustomTemplateContext) => void;
不知道我说清楚没，意思是，你可以在这个文件里 export 它，方便单元测试，但不要在 index.ts 中 export 这个接口了。

2021-09-15 06:15 UTC, weareoutman approved these changes

2021-09-15 06:19 UTC, merged